# Generated by Django 5.0.1 on 2024-03-02 07:10

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
